[package]
name = "elementary-rust-example"
version = "0.1.0"
edition = "2021"

[dependencies]
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.6", package = "gtk4", features = ["v4_6"] }
granite = { version = "0.2", package = "granite-rs", features = ["v7_2"] }
once_cell = "1.0"

