name: Update Flatpak Modules

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'Cargo.lock'

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: repo

    - uses: actions/checkout@v3
      with:
        repository: flatpak/flatpak-builder-tools
        path: tools

    - name: Update modules
      run: |
        sudo apt-get install -y python3-toml python3-aiohttp
        python3 tools/cargo/flatpak-cargo-generator.py -o repo/cargo-sources.json repo/Cargo.lock
    - run: |
        cd repo
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add cargo-sources.json
        git commit -m "Update cargo-sources.json"
        git push
